executable = Expectations.sh
arguments = $(Process)

container_image = docker://alexandermiller019/rida:primary
universe = container

log = RIDA_$(Cluster)_$(Process).log
error = RIDA_$(Cluster)_$(Process).err
output = RIDA_$(Cluster)_$(Process).out

transfer_input_files = Expectations.py

should_transfer_files = YES

request_cpus = 1
request_memory = 1GB
request_disk = 1GB

queue 4